import type { Client } from '@/lib/types';

/**
 * Organisations shipped for, as shown in the s03 client grid.
 *
 * Names come from the previous site's own records, cross-checked against the
 * link domain each one carried. That check matters: the old site paired the
 * KPKM crest and kpkm.gov.my with "Kolej Profesional Mara Kuala Nerang", which
 * is a different organisation entirely. It is the ministry. Every other entry
 * agreed with its domain.
 *
 * `logo` points at public/img/clients-mono, NOT public/img/clients. Those are
 * generated by scripts/normalise-client-logos.py: the source artwork is full
 * colour at aspect ratios from 7.32:1 to 0.82:1, half of it too dark to see on
 * the page background, and no single CSS filter can fix that. The generated set
 * is greyscaled, weight-matched and centred on one canvas so the grid needs no
 * per-logo overrides.
 */
export const CLIENTS_HEAD = {
  title: 'DEPLOYED FOR',
  note: '12 ORGANISATIONS',
} as const;

export const CLIENTS: readonly Client[] = [
  { slug: 'csm', name: 'Cyber Security Malaysia', short: 'CSM' },
  { slug: 'penjara', name: 'Penjara Kajang', short: 'PENJARA KAJANG' },
  { slug: 'kpkm', name: 'Kementerian Pertanian dan Keterjaminan Makanan', short: 'KPKM' },
  { slug: 'dof', name: 'Department of Fisheries Malaysia', short: 'DOF' },
  { slug: 'umpsa', name: 'Universiti Malaysia Pahang Al-Sultan Abdullah', short: 'UMPSA' },
  { slug: 'topglove', name: 'Top Glove Corporation Bhd.', short: 'TOP GLOVE' },
  { slug: 'kaneka', name: 'Kaneka Corporation', short: 'KANEKA' },
  { slug: 'gapura', name: 'Gapura Solution Sdn. Bhd.', short: 'GAPURA' },
  { slug: 'satok', name: 'Satok Bridge Digital Sdn. Bhd.', short: 'SATOK BRIDGE' },
  { slug: 'sasaqua', name: 'Serandu Aquaponic System', short: 'SAS' },
  { slug: 'fugen', name: 'Fugen Legacy', short: 'FUGEN' },
  { slug: 'justgood', name: 'JustGood', short: 'JUSTGOOD' },
] as const;
